spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/insight?serverTimezone=Asia/Seoul&useUnicode=true?characterEncoding=utf-8
      username: root
      password: 1234
      connection-test-query: select 1
  thymeleaf:
    cache: false
  resources:
    cache:
      period: 0
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true # JPA의 엔티티 연관관계를 바탕으로 테이블 생성과 같은 스크립트(DDL)를 자동 실행하도록 설정, 실제 개발에서는 false로 사용
    hibernate:
      use-new-id-generator-mappings: false  # 하이버네이트의 새로운 ID 생성 옵션의 사용 여부 설정/ AUTO, TABLE, SEQUENCE가 있음/ MySQL의 자동증가(Auto Increment) 속성을 사용하기 때문에 FALSE로 설정
    show-sql: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true


